#---
bacteria: bac_uniquespecies_giant.masked_Ns_removed.fasta
contaminants: vector_contaminants.fa.gz
host: human_virus_masked.fasta

# temp fix
Mem: 64 # Gb
Threads: 16

QSCORE: 15 # Read quality trimming score (rule remove_low_quality in 00_preprocessing.smk)
MINLENGTH: 100 # Read minimum length (rule remove_low_quality in 00_preprocessing.smk)
ENTROPY: 0.5 # Read minimum entropy (rule remove_low_quality in 00_preprocessing.smk)
CLUSTERID: 0.95 # Linclust read clustering percent identity (rule cluster_similar_sequences: in 00_preprocessing.smk)
CONTIG_SIZE_THRESH: 500 # Minimum allowable contig size

# URLs and checksums for databases
url:
  hecatomb:
    filename: "hecatomb.databases.tar.zst"
    tar:      "https://cloudstor.aarnet.edu.au/plus/s/A4Swxf13wES8Uez/download"
    md5:      "https://cloudstor.aarnet.edu.au/plus/s/vnilMkcFLQTDqB4/download"
  uniprot_virus:
    filename: "uniprot_virus_c99.tar.zst"
    tar:      "https://cloudstor.aarnet.edu.au/plus/s/PLoGhe47HmFgosv/download"
    md5:      "https://cloudstor.aarnet.edu.au/plus/s/UigsJNrKF8tvjC6/download"
  uniref50:
    "ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref50/uniref50.fasta.gz"
  id_map:
    filename: "uniprot_ncbi_mapping.dat.zst"
    zst:      "https://cloudstor.aarnet.edu.au/plus/s/nASd4zM3RfDvbux/download"
    md5:      "https://cloudstor.aarnet.edu.au/plus/s/pgCGnu7pei4pHOC/download"
  hecatomb_nucl:
    filename: "hecatomb.nucleotide.databases.tar.zst"
    tar:      "https://cloudstor.aarnet.edu.au/plus/s/30agxBFKqlj3bm3/download"
    md5:      "https://cloudstor.aarnet.edu.au/plus/s/WjLjPMkkR59AaQE/download"
  taxonomizer:
    filename: "taxonomizr_accessionTaxa.sql.zst"
    zst:      "https://cloudstor.aarnet.edu.au/plus/s/ox7yIlWxhwpmGUy/download"
    md5:      "https://cloudstor.aarnet.edu.au/plus/s/aR4VCCF0cA4l2R4/download"
  taxdump:
    filename: "taxdump.tar.gz"
    tar:      "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz"
    md5:      "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz.md5"
  ntacc2tax:
    filename: "nucl_gb.accession2taxid.gz"
    gz:       "ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz"
    md5:      "ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz.md5"
  lineSine:
    filename: "line_sine.fasta.zst"
    zst:      "https://cloudstor.aarnet.edu.au/plus/s/wXyN3AJX47hEDnF/download"
    md5:      "https://cloudstor.aarnet.edu.au/plus/s/EiQQOKJ3jByD482/download"
