# generic settings
jobs: 10
#use-conda: True
#conda-frontend: mamba
default-resources: [cpus=1, mem_mb=2000]
keep-going: True

# sge settings
cluster: "qsub -cwd -o sge_out -e sge_err -pe smp {resources.cpus} -V "
latency-wait: 60
local-cores: 8
