Paths:
  # The Reads directory has your input fastq files that you want to process through hecatomb
  Reads: test_data/fastq

# Temporary directory.
Temp: tmp
# log directory for slurm etc. Only change if you changed the directory name in slurm.yaml
Logs: logs
# The Database directory, UNCOMMENT AND UPDATE ONLY IF YOU WANT TO MANUALLY RUN THE SNAKEMAKE PIPELINES
#Databases: databases

DatabaseFiles:
  # Predefined databases for screening. You may want to replace host with e.g. mouse
  bacteria: bac_uniquespecies_giant.masked_Ns_removed.fasta
  contaminants: vector_contaminants.fa.gz
  host: human_virus_masked.fasta
  #host: mouse_virus_masked.fasta
  #host: other_virus_masked.fasta

Options:
  # run_prinseq first cleans the reads with prinseq++
  run_prinseq: True
  # use_bowtie substitutes bowtie2 and samtools for bbmap
  use_bowtie: True

Output:
  # Clumped is where the clumpify output of the original reads is written. QC is the output for all the QC steps
  Clumped: clumped
  QC: QC
  Results: results

System:
  # How much memory you want to allocate to java
  Memory: -Xmx128g
