# generic settings
jobs: 10
use-conda: True
conda-frontend: mamba
default-resources: [cpus=1, mem_mb=2000, time_min=0-01:00:00]
keep-going: True

# slurm settings
cluster: "sbatch -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o logs/{rule}_{jobid}.out -e logs/{rule}_{jobid}.err "
latency-wait: 60
local-cores: 8
